# numpy

## 속도 비교

In [5]:
import numpy as np
import datetime

In [9]:
# list의 작업 시간
li = range(1,1000000)

# 현재 시간 저장
s = datetime.datetime.now()
print("시작시간:",s)

# 모든 요소에 10을 곱해서 list를 수정
for i in li :
    i = i * 10
    
# 현재 시간 저장
s = datetime.datetime.now()
print("종료시간:",s)

시작시간: 2023-08-07 15:26:49.161080
종료시간: 2023-08-07 15:26:49.307865


In [10]:
ar = np.arange(1,1000000)
s = datetime.datetime.now()
print("시작시간:",s)
ar = ar * 10
s = datetime.datetime.now()
print("종료시간:",s)

시작시간: 2023-08-07 15:26:51.007886
종료시간: 2023-08-07 15:26:51.010098


In [12]:
# 배열 정보 확인
ar = np.array([1,2,3])
print(type(ar)) #ar의 자료형
print(ar.dtype) #ar에 저장된 요소의 자료형
print(ar.ndim) #일차원 배열
print(ar.shape) #3개의 행으로 구성


<class 'numpy.ndarray'>
int32
1
(3,)


In [13]:
ar = np.array([[1,2,3],[4,5,6]])
print(ar.ndim) #2
print(ar.shape) #2행3열


2
(2, 3)


In [19]:
ar = np.arange(1,100,2)
print(ar)
ar = np.linspace(1,100,num=10) #num은 개수
print(ar)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [24]:
# eye - 대각선 방향으로 1을 채운 행렬
ar = np.eye(3) # 3*3 행렬을 생성하고 대각선 방향으로 1을 채움
print(ar)
ar = np.eye(3,k=1) # 3*3 행렬을 생성하고 대각선 방향으로 1을 채우는데 기본에서 위로
print(ar)
ar = np.eye(3,k=-1) # 3*3 행렬을 생성하고 대각선 방향으로 1을 채우고 기본에서 아래로
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [28]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)
br = np.diag(ar) # 대각선 방향이므로 1,5,9
print(br)
cr = np.diag(ar,k=-1) # 기본 대각선에서 하나 아래로 내려가므로 4,8
print(cr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
[4 8]


In [53]:
import numpy as np
ar = np.array([1,2,'3']) # 문자열로 배열이 생성
print(ar)
#자료형을 지정해서 생성
ar = np.array([1,2,'3'], dtype=np.int32) #정수로 배열이 생성 - 자료형 지정
print(ar)

ar = np.array([1,2,'3']) # 문자열로 배열이 생성
print(ar)

br = ar.astype(np.int32) # 기존 배열의 자료형을 변경해서 생성
print(br)

['1' '2' '3']
[1 2 3]
['1' '2' '3']
[1 2 3]


In [45]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
ar = matrix.reshape(-1) # 1차원으로 변환 : 접근 방법을 변환한 것이라서 이전과 동일한 데이터

print(ar)
ar[5]=101
print(matrix)

br = matrix.flatten() # 복제를 해서 1차원으로 변경 - 원본과 다른 데이터
print(br)
br[0] = 201
print(matrix) # 201로 안바뀜

[1 2 3 4 5 6 7 8 9]
[[  1   2   3]
 [  4   5 101]
 [  7   8   9]]
[  1   2   3   4   5 101   7   8   9]
[[  1   2   3]
 [  4   5 101]
 [  7   8   9]]


In [66]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix) # 전체 출력
print(matrix[0][1]) #0번째 행에 1번째 열
print(matrix[0]) #0번째 행을 선택할 때는 열 인덱스를 제외
print(matrix[:,0]) #0번째 열을 선택할 때는 행의 전체라고 설정을 해야 함
# 행렬 구조가 있을 때 행을 먼저 선택하고 열을 선택하기 때문에 행은 생략할 수 없음
print(matrix[0:2]) #0번째 행부터 2번째 행 앞 까지
# 일반 인덱싱은 참조를 복사
x = matrix[0][0]
print(x)
print(matrix[0][0])
# 현재는 둘 다 1

x = 1004
print(x)
print(matrix[0][0]) # [행번호][열번호] 이렇게 접근하는 경우는 슬라이싱이라고 하고
# [행번호, 열번호] 이렇게 접근하는 것이 인덱싱
# 슬라이싱은 복제를 함
# 인덱싱은 참조를 복사



[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[1 2 3]
[1 4 7]
[[1 2 3]
 [4 5 6]]
1
1
1004
1


In [73]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

# 0번 행을 인덱싱 - 참조를 복사
ar = matrix[0]
br = matrix[0,]
print(ar) # [1,2,3]
print(br)

# ar의 0번째 요소를 100으로 수정
ar[0]=100
print(ar) #[100,2,3]
print(br) #[100,2,3]
print(matrix) #[100,2,3]

# list를 이용하는 인덱싱을 팬시 인덱싱이라고 함
cr = matrix[[0]]
# 범위를 이용하는 형태를 슬라이싱이라고 함
dr = matrix[0][:]
# 팬시 인덱싱과 슬라이싱은 복제를 함
# 복제된 데이터를 수정해도 원본에 영향을 주지 않음
print(cr)
print(dr)
cr[0,0] = 1004
print(cr) # [[1004,2,3]]
print(dr) # [100,2,3]
print(matrix) # [[100,2,30],[4,5,6],[7,8,9]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[1 2 3]
[100   2   3]
[100   2   3]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
[[100   2   3]]
[100   2   3]
[[1004    2    3]]
[100   2   3]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [77]:
ar = np.array([10,2,30,5,22,37])
br = np.array([1,2,3,4,5,6])

print(br[(ar >= 30) | (ar <= 10)])
# print(br[(ar >= 30) or (ar <= 10)]) -> 오류

[1 2 3 4 6]
