In [2]:
import numpy as np # numpy 모듈을 np라는 이름으로 가져오는 것

In [3]:
# 일차원 배열과 이차원 배열 생성
li = list(range(1,10)) # 일차원 list 생성
print(li)

# list를 이용해서 ndarray 생성
ar = np.array(li)
print(ar)

# 일차원 배열을 생성한 후 행과 열의 개수를 3 * 3 으로 변경
matrix = np.array(li).reshape((3,3))
print(matrix)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
# 인덱싱 - 데이터 1개 가져오기
data1 = ar[0] # data1 = 1
print(data1)
data2 = matrix[0,0]
data3 = matrix[0][0]
print(data2)
print(data3)

# 이차원 배열에서 행 하나 찾아오기
row = matrix[0] # matrix[0][:], matrix[0,:]
print(row)

# 이차원 배열에서 열 하나 찾아오기
column = matrix[:,0] 
print(column)



1
1004
1004
[1004    2    3]
[1004    2    3]


In [ ]:
# 파이썬에서의 데이터 복사

In [9]:
# 파이썬에서의 데이터 복사

# 일반 인덱싱한 데이터는 파이썬의 기본 데이터와 동일하게 동작을 함
# 파이썬의 scala data는 일반적으로 immutable
# scala data는 다른 변수에 대입할 때 값을 복사해서 대입
a = 10
b = a
b = 20
print(a)

# 파이썬의 vector data는 다른 변수에 대입할 때 참조를 복사해서 대입
ax = [1,2,3]
bx = ax  # bx 는 [1,2,3]의 참조
bx[0] = 100
print(ax)

10
[100, 2, 3]


In [16]:
# 파이썬에서의 데이터 복제
# copy 모듈의 copy(shallow copy - 얕은 복사)와 deepcopy(깊은 복사) 함수 이용
# 얕은 복사는 한 번은 복제를 하지만 재귀적으로 수행하지 않음
# 깊은 복사는 재귀적으로 복제를 수행

import copy

li = [1,2,3]

c = li.copy() # 얕은 복사
c[0] = 100 # 1차원 list의 경우는 원본에 영향을 주지 않음
print(li)

m = [[1,2,3],[4,5,6]]
c = m.copy() # 얕은 복사는 이차원 배열의 경우는 원본에 영향을 줌
c[0][0] = 100
print(m)

# copy.deepcopy는 재귀적으로 복제를 수행하기 때문에
# 복사본의 데이터를 수정해도 원본에는 영향이 없음
d = copy.deepcopy(m)
print(d)
d[0][0] = 10004
print(m)

[1, 2, 3]
[[100, 2, 3], [4, 5, 6]]
[[100, 2, 3], [4, 5, 6]]
[[100, 2, 3], [4, 5, 6]]


In [19]:
# scala data를 복사하는 경우는 원본의 값을 복사해서 대입하기 때문에
# 서로 간에 영향을 주지 않음

data1 = 1000
print(data1)
print(ar)

data2 = 1000
print(data2)
print(matrix)

# row는 scala data(preemitive type)가 아니고 vector data
# vector 데이터를 다른 곳에 대입하면 참조가 복사됨
# 복사본을 수정하면 원본도 영향을 받음

row[0] = 1004
print(row)
print(matrix)

# 데이터 복제는 copy() 메서드
clone = matrix.copy()
clone[0][0] = 42 # 복사본의 데이터를 수정해도 원본에서는 그대로 1004
print(matrix)

1000
[1 2 3 4 5 6 7 8 9]
1000
[[1004    2    3]
 [   4    5    6]
 [   7    8    9]]
[1004    2    3]
[[1004    2    3]
 [   4    5    6]
 [   7    8    9]]
[[1004    2    3]
 [   4    5    6]
 [   7    8    9]]


In [26]:
li = [1,2,3,4,5]
c = li[0:3] # list의 슬라이싱 : 얕은 복사 수행
# c 와 li는 앞 3개의 데이터가 동일하지만 다른 공간의 데이터
print(c)
print(c is li)
c[0] = 100 # c의 값을 변경해도 li에는 영향이 없음
print(li)

ar = np.array(li)
d = ar[0:3] # 배열에서 0 번째부터 2 번째 까지 데이터를 복사
# 0번째부터 2번째이므로 이 데이터는 3개(vector data)
# 참조가 복사
print(d)
print(d is ar)
d[0] = 100 # d의 값을 수정하면 원본에 영향을 주게 됨
print(ar)


[1, 2, 3]
False
[1, 2, 3, 4, 5]
[1 2 3]
False
[100   2   3   4   5]


In [ ]:
# Fancy Indexing

In [28]:
# 인덱싱을 할 때 list를 이용하는 것
ar = np.array([100,200,300,400,500])
f = ar[[0,2]]
print(f)
f[0] = 1004
print(ar)

[100 300]
[100 200 300 400 500]


In [33]:
# 불리언 색인 : array의 인덱스에 bool 배열을 대입해서 True인 데이터만 골라내기
# 조건에 맞는 데이터만 추출할 때 사용

ar = np.array([1,2,3,4,5,6,7])
result = ar[[True, True, False, False, True, False, True]]
print(result)

br = np.array([100,20,30,40,50,80,90])
result = ar[br >= 70]
print(result)

br = np.array([100,20,30,40,50,80,90])
result = ar[(br >= 70) & (br <=90)]
print(result)


[1 2 5 7]
[1 6 7]
[6 7]


# ndarray 의 연산

In [38]:
ar = np.array([1,2,3,4,5])
br = np.array([1,2,3,4,5])
cr = np.array([1,2,3,4])

print(ar + br)
# print(ar + cr) 에러 
print(ar + 1)


[ 2  4  6  8 10]
[2 3 4 5 6]


In [47]:
ar = np.array([1,2,3,4,5])
br = np.array([10,20,30,40,50])

result = ar + br
print(result)

result = ar + 4 # 2개의 차원이 다른 경우로, 이 경우 적은 차원의 데이터를 큰 차원으로 수정
# ar + [4,4,4,4]
print(result)

k = range(1,11)
# print(ar + np.array(k))는 에러
# 1차원 배열을 2행 5열로 수정해서 연산을 수행
cr = np.array(k).reshape(2,5)
print(ar+cr)


[11 22 33 44 55]
[5 6 7 8 9]
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


In [49]:
# 논리 연산
ar = np.array([1,2,3,4,5])
br = np.array([10,20,False,40,0])

print(ar > br)
print(np.not_equal(ar,br))
print(np.logical_xor(ar,br)) # and, or, xor 는 bool(True, False)로 변경해서 판정

[False False  True False  True]
[ True  True  True  True  True]
[False False  True False  True]


In [53]:
ar = np.array([1,2,3,4,5])
br = np.array([10,20,False,40,0])

ar += br # ar = ar + br
print(ar)

print(11 in ar)
print([11,22] in ar)
print([1,100] in ar)

[11 22  3 44  5]
True
False
False


C:\Users\USER\AppData\Local\Temp\ipykernel_8108\623138640.py:8: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print([11,22] in ar)
C:\Users\USER\AppData\Local\Temp\ipykernel_8108\623138640.py:9: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print([1,100] in ar)


In [62]:
# 벡터화된 함수 적용
# 매개변수에 100을 더해서 리턴하는 함수

def f(i) :
    return i + 100

# 벡터화된 함수로 수정
vector_f = np.vectorize(f)

# 배열에 벡터화된 함수 적용
print(vector_f(ar))

# 람다 함수(파이썬의 한 줄 짜리 이름없는 함수)를 이용해서 동일한 작업 수행
print(np.vectorize(lambda i : i + 100)(ar))




[101 102 103 104 105]
[101 102 103 104 105]


In [66]:
matrix = np.array(range(1,11)).reshape((5,2))
print(matrix)
print(matrix.reshape((2,5))) # 행과 열의 수를 변경해서 전치
print(matrix.T) # 행과 열을 변경
print(np.transpose(matrix)) # 행과 열을 변경

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [86]:
np.random.seed(seed=42) # seed 고정

cards = np.array(range(1,49)) # 1부터 48까지의 일차원 배열
print(cards)

# 배열을 섞어서 리턴
np.random.shuffle(cards)
print(cards)

result = np.random.permutation(cards)
print(cards)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[28 41 27 44 25 38 13 20  5 26  9  4  7 40 34 14 18 46 16 10 17 30 33 47
  1 32 31  6 12 35  2 45 22  3 37 36 24 42 11 23 19 48 21  8 43 15 29 39]
[28 41 27 44 25 38 13 20  5 26  9  4  7 40 34 14 18 46 16 10 17 30 33 47
  1 32 31  6 12 35  2 45 22  3 37 36 24 42 11 23 19 48 21  8 43 15 29 39]


In [98]:
# 기본 통계 함수
matrix = np.random.randn(20).reshape((4,5))
print(matrix)
print(matrix.sum())
print(matrix.std()) # 표준 편차
print(matrix.std(ddof=1)) # 표준 편차 - 자유도 1 적용
print(np.percentile(matrix,75)) # 75%에 해당하는 값

# 행단위와 열단위 합계
print(matrix.sum(axis=0))
print(matrix.sum(axis=1))
print(matrix.sum(axis=1, keepdims=True)) # 행 단위 - matrix와 동일한 차원으로 리턴
print(matrix.sum(axis=0, keepdims=True)) # 열 단위 - matrix와 동일한 차원으로 리턴


print(matrix.argmax(axis=1))
print(matrix.prod(axis=0))


[[-0.03582604  1.56464366 -2.6197451   0.8219025   0.08704707]
 [-0.29900735  0.09176078 -1.98756891 -0.21967189  0.35711257]
 [ 1.47789404 -0.51827022 -0.8084936  -0.50175704  0.91540212]
 [ 0.32875111 -0.5297602   0.51326743  0.09707755  0.96864499]]
-0.2965965430501677
1.0002805249964482
1.0262661646587288
0.590426200928823
[ 1.47181176  0.60837401 -4.90254019  0.19755112  2.32820675]
[-0.18197791 -2.0573748   0.5647753   1.37798088]
[[-0.18197791]
 [-2.0573748 ]
 [ 0.5647753 ]
 [ 1.37798088]]
[[ 1.47181176  0.60837401 -4.90254019  0.19755112  2.32820675]]
[1 4 0 4]
[ 0.00520465  0.03941923 -2.16073512  0.00879442  0.02756359]


In [100]:
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si

In [103]:
# 일차원 배열의 정렬
ar = np.array([20,30,10,25,27])
result = np.sort(ar)
print(result)
print(ar)

# 2차원 배열에서 행에서의 정렬
br = np.array([[10,60,80],[20,50,30],[15,32,29]])
result = np.sort(br,axis=1)
print(result)





[10 20 25 27 30]
[20 30 10 25 27]
[[10 60 80]
 [20 30 50]
 [15 29 32]]


In [122]:
x = range(1,51)
# 위의 데이터를 가지고 10행 5열 짜리 이차원 배열 생성
# 데이터를 가지고 7:3 분할 : numpy.split
ar = np.array(x)
matrix = ar.reshape((10,5))
print(matrix)

# 행과 열의 개수 가져오기
print(matrix.shape)
print(type(matrix.shape))

cnt = matrix.shape[0]
print(cnt) # 행의 개수 출력(10)

#help(np.split)

# 여기에 permutation을 적용하면 샘플링 해주는 함수가 됨
# 행의 개수 * 0.7 하면 7:3 적용 가능(int처리 꼭 해줘야 함)
ar_s = np.split(matrix,[int(cnt * 0.7),])
print(ar_s[0])
print(ar_s[1])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
(10, 5)
<class 'tuple'>
10
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [123]:
import numpy as np
import pandas as pd

In [127]:
series1 = pd.Series([10,20,30,40]) # 인덱스 없이 0,1,2,3 으로 접근하도록 생성
# 인덱스와 함께 생성
series2 = pd.Series([10,20,30,40], index = ["one", "two", "three", "four"])
print(series1)
print(series2)
# dict를 이용해서 key는 index가 value는 value가 되도록 설정
series3 = pd.Series({"태연":"소녀시대", "수지":"Miss A", "카리나":"aespa", "설현" : "AOA"})
print(series3)

0    10
1    20
2    30
3    40
dtype: int64
one      10
two      20
three    30
four     40
dtype: int64
태연       소녀시대
수지     Miss A
카리나     aespa
설현        AOA
dtype: object


In [129]:
# 인덱싱
print(series3[0]) # 일련 번호를 가지고 접근
print(series3["태연"]) # 인덱스를 가지고 접근
print(series3[0:2]) # 일련 번호는 종료 위치가 포함되지 않음
print(series3["태연":"카리나"]) #인덱스는 종료 위치가 포함됨

소녀시대
소녀시대
태연      소녀시대
수지    Miss A
dtype: object
태연       소녀시대
수지     Miss A
카리나     aespa
dtype: object


In [132]:
print(series1.values) # 값들만 추출
print(series1 + 100 ) # 연산은 numpy의 ndarray와 동일하게 수행되는데 values 속성의 멤버를 가지고 연산
print(np.sum(series1))


[10 20 30 40]
0    110
1    120
2    130
3    140
dtype: int64
100


In [137]:
s1 = pd.Series({"태연":81, "수지":99,"카리나":88,"설현":73})
s2 = pd.Series({"태연":np.nan,"카리나":77, "수지":98,"민지":59})
print(s1)
print(s2)
print(s1 + s2)

태연     81
수지     99
카리나    88
설현     73
dtype: int64
태연      NaN
카리나    77.0
수지     98.0
민지     59.0
dtype: float64
민지       NaN
설현       NaN
수지     197.0
카리나    165.0
태연       NaN
dtype: float64


In [138]:
# DataFrame을 만들기 위한 디셔너리 생성
items = {
    'code':[1,2,3,4],
    'name':['수박','키위','자두','참외'],
    'price':[30000,2500,1500,2000]
}

df = pd.DataFrame(items)
print(df)



   code name  price
0     1   수박  30000
1     2   키위   2500
2     3   자두   1500
3     4   참외   2000


In [143]:
print(df.index)
print(df.columns)
df.index = range(1,5)
print(df.index)
df.columns = ['코드','이름','가격']
print(df.columns)
print(df)



RangeIndex(start=1, stop=5, step=1)
Index(['코드', '이름', '가격'], dtype='object')
RangeIndex(start=1, stop=5, step=1)
Index(['코드', '이름', '가격'], dtype='object')
   코드  이름     가격
1   1  수박  30000
2   2  키위   2500
3   3  자두   1500
4   4  참외   2000


In [150]:
# head나 tail 함수는 데이터가 제대로 불러져 왔는지 확인할 때 이용

print(df.head(2))
print(df.tail(2))

# 이 데이터를 머신러닝을 하고자 하면 머신러닝은 numpy의 ndarray 로만 가능
print(type(df.values)) # values : 데이터를 2차원 배열(ndarray)로 리턴
# 데이터 분석을 하기 전에 데이터를 가져왔으면 데이터에 대한 정보를 확인
df.info() # info : 데이터 프레임에 대한 정보 확인


   코드  이름     가격
1   1  수박  30000
2   2  키위   2500
   코드  이름    가격
3   3  자두  1500
4   4  참외  2000
<class 'numpy.ndarray'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 1 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   코드      4 non-null      int64 
 1   이름      4 non-null      object
 2   가격      4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes


In [152]:
import numpy as np
import pandas as pd

# 현재 작업 디렉토리 확인
import os
print(os.getcwd())



C:\Users\USER


In [161]:
items = pd.read_csv('C:/Users/USER/data/data/item.csv', index_col='code')
print(items)

      manufacture            name  price
code                                    
1           korea           apple   1500
2           korea      watermelon  15000
3           korea  oriental melon   1000
4     philippines          banana    500
5           korea           lemon   1500
6           korea           mango    700


In [163]:
# good.csv는 첫 번째 행도 일반 데이터 이므로
# 첫 번째 행이 헤더가 아니라고 설정하고 names를 이용해서 헤더 이름을 설정
goods = pd.read_csv('C:/Users/USER/data/data/good.csv', header=None, names=['제품명','개수','가격'])
print(goods)

      제품명  개수     가격
0   apple  10   1500
1  banana   5  15000
2   melon   7   1000
3    kiwi  20    500
4   mango  30   1500
5  orange   4    700


In [168]:
# 3개씩 읽어오도록 설정
goods = pd.read_csv('C:/Users/USER/data/data/good.csv', header=None, chunksize=3)
for piece in goods:
    print(type(piece))
    print(piece)
    print()

<class 'pandas.core.frame.DataFrame'>
        0   1      2
0   apple  10   1500
1  banana   5  15000
2   melon   7   1000

<class 'pandas.core.frame.DataFrame'>
        0   1     2
3    kiwi  20   500
4   mango  30  1500
5  orange   4   700



In [172]:
goods = pd.read_csv('C:/Users/USER/data/data/gapminder.tsv',sep='\t')
print(goods)

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]


In [181]:
import numpy as np
import pandas as pd
test = pd.read_csv('C:/Users/USER/data/data/fruit.csv',sep='|')
print(test)

    apple  10   1500
0  banana   5  15000
1  orange  20    500
2    pear  30   1500
3    kiwi   7   1000
4   mango   4    700
